In [1]:
import numpy as np
from agent import Agent
import neural_net
from graphics import display_grid
from utils import generate_array, in_bounds
import new_grid as grid

In [2]:
# these are the test grids given to humans

test3 = {"train": (0, 3), "trainvel": (1, 0), "cargo1": (2, 2), "target1": (0, 4), "switch": (2, 4), "agent": (2, 0), "cargo2": (3, 3), "target2": (3, 4),'num1':1,
    'num2':2}

test12 = {"train": (1, 0), "trainvel": (0, 1), "cargo1": (2, 2), "target1": (3, 1), "switch": (0, 4), "agent": (3, 1), "cargo2": (1, 4), "target2": (0, 3), 'num1':1, 'num2':2}

test14 = {"train": (4, 4), "trainvel": (-1, 0), "cargo1": (1, 3), "target1": (3, 2), "switch": (4, 1), "agent": (0, 2), "cargo2": (0, 4), "target2": (0, 1), 'num1':1,
    'num2':2}

test_suite = [grid.Grid(5,random=False, init_pos=test3),
              grid.Grid(5,random=False, init_pos=test12),
              grid.Grid(5,random=False, init_pos=test14)]
agent = Agent()

In [3]:
# Running the test grids on model free model

for test in test_suite:
    agent.run_model_free_policy(test.copy(), display=True)

[['a' '_' 'S' 'b' '_']
 ['>' '_' '_' '2' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '◉' '_' '_']]
=====
neural net loaded
[[-1.2388649 -0.995709  -1.1386845 -1.2613984 -1.1319646]]
(-1, 0)
[['a' '_' 'S' 'b' '_']
 ['_' '>' '_' '2' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '◉' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
[[-1.5345002 -1.722619  -1.5306541 -1.2840523 -1.3045087]]
(1, 0)
[['a' '_' 'S' 'b' '_']
 ['_' '_' '>' '2' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '◉' '_' '_']]
=====
[[-1.9595971 -1.6752486 -2.0144281 -1.8655545 -1.6491158]]
(0, -1)
[['a' '_' 'S' 'b' '_']
 ['_' '_' '_' 'x' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '◉' '_' '_' '_']]
=====
[[ 0.02727392  0.07445832 -0.03146613  0.06191657 -0.00802704]]
(-1, 0)
[['a' '_' 'S' 'b' '_']
 ['_' '_' '_' 'x' '_']
 ['_' '_' '1' '_' '_']
 ['_' '◉' '_' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
[[-0.00047752  0.06678986 -0.00502804 -0.01150718 -0.03047552]]
(-1, 0)
[['a' '_' 'S' 'b' '_']
 ['_'

The test scenarios all involve pushing cargo that is worth less into the path of cargo that is worth more. The model free system does not do that, which is as expected.

In [5]:
# Now testing the dual model operation
for test in test_suite:
    Q, policy = agent.mc_first_visit_control(test.copy(), iters=200, nn_init=True,cutoff=0.4,softmax = True)
    agent.run_final_policy(test.copy(), Q,nn_init=True,display=True)

[['a' '_' 'S' 'b' '_']
 ['>' '_' '_' '2' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '◉' '_' '_']]
=====
(-1, 0)
[['a' '_' 'S' 'b' '_']
 ['_' '>' '_' '2' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '◉' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
(-1, 0)
[['a' '_' 'S' 'b' '_']
 ['_' '_' 'x' '2' '_']
 ['_' '_' '◉' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
(0, 1)
[['a' '_' 'S' 'b' '_']
 ['_' '_' 'x' '2' '_']
 ['_' '_' '_' '◉' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
(-1, 0)
[['a' '_' 'S' '2' '_']
 ['_' '_' 'x' '◉' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_']
 ['_' '_' '_' '_' '_']]
=====
(-1, 0)
1
[['S' '2' '_' '_' '_']
 ['b' '_' '_' '_' '_']
 ['_' '_' '1' '_' '_']
 ['_' '_' '_' '◉' '_']
 ['_' '^' '_' '_' '_']]
=====
(-1, 0)
[['S' '2' '_' '_' '_']
 ['b' '_' '_' '_' '_']
 ['_' '_' '1' '◉' '_']
 ['_' '^' '_' 'a' '_']
 ['_' '_' '_' '_' '_']]
=====
(0, -1)
[['S' '2' '_' '_' '_']
 ['b' '_' '_' '_' '_']
 ['_' 'x' '◉' '_' '_']
 ['_' '_' '_' 'a' '_

At 200 iterations, the dual model reliably pushes the cheaper cargo into the path of the train.
At 20 iterations, the dual model behaves the same as the model free solution.